version: "3.9"
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_URI=mongodb://localhost:27017/mycollection
    
  fastapi:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    
